export const siteConfig = {
  name: "Reactify Cheque Printer System",
  description: "Prepare and print Nepalese bank cheques with precise alignment.",
  url: process.env.NEXT_PUBLIC_APP_URL || "http://localhost:3000",
  logo: "/logos/reactify-logo.svg",
  company: "Reactify Software Technologies Pvt. Ltd.",
  contact: {
    phone: "+977-9743836026",
    phoneHours: "Sun–Fri, 10am–5pm",
    email: "info@reactifysoftwaretechnologies.com.np",
    address: "Kankai Municipality-3, Campus Road, Surunga, Jhapa, Nepal",
    website: "www.reactifysoftwaretechnologies.com.np",
  },
  navItems: [
    { label: "Home", labelKey: "home", href: "/" },
    { label: "Features", labelKey: "features", href: "/features" },
    { label: "Pricing", labelKey: "pricing", href: "/pricing" },
    { label: "About", labelKey: "about", href: "/about" },
    { label: "Contact", labelKey: "contact", href: "/contact" },
  ],
  dashboardNavItems: [
    { label: "Dashboard", labelKey: "dashboard", href: "/dashboard", icon: "LayoutDashboard" },
    {
      label: "Print Cheque",
      labelKey: "newCheque",
      href: "/dashboard/cheques/new",
      icon: "Printer",
    },
    { label: "My Cheques", labelKey: "myCheques", href: "/dashboard/cheques", icon: "FileText" },
    {
      label: "Templates",
      labelKey: "templates",
      href: "/dashboard/templates",
      icon: "LayoutTemplate",
    },
    { label: "History", labelKey: "history", href: "/dashboard/history", icon: "Clock" },
    { label: "Payees", labelKey: "payees", href: "/dashboard/payees", icon: "Users" },
    { label: "Assistant", labelKey: "assistant", href: "/dashboard/assistant", icon: "Bot" },
    { label: "Profile", labelKey: "profile", href: "/dashboard/profile", icon: "User" },
    {
      label: "Subscription",
      labelKey: "subscription",
      href: "/dashboard/subscription",
      icon: "CreditCard",
    },
    { label: "Settings", labelKey: "settings", href: "/dashboard/settings", icon: "Settings" },
  ],
  adminNavItems: [
    { label: "Dashboard", labelKey: "dashboard", href: "/admin", icon: "LayoutDashboard" },
    {
      label: "Pending Payments",
      labelKey: "pendingPayments",
      href: "/admin/payments",
      icon: "CreditCard",
    },
    { label: "Users", labelKey: "users", href: "/admin/users", icon: "Users" },
    { label: "Banks", labelKey: "banks", href: "/admin/banks", icon: "Building2" },
    {
      label: "Templates",
      labelKey: "templates",
      href: "/admin/templates",
      icon: "LayoutTemplate",
    },
    { label: "Audit Logs", labelKey: "auditLogs", href: "/admin/audit-logs", icon: "BarChart3" },
    { label: "Settings", labelKey: "settings", href: "/admin/settings", icon: "Settings" },
    { label: "Plans", labelKey: "plans", href: "/admin/plans", icon: "CreditCard" },
    { label: "Reports", labelKey: "reports", href: "/admin/reports", icon: "BarChart3" },
  ],
  pricing: {
    trial: {
      label: "Free Trial",
      price: "Free",
      duration: "14 days",
      features: ["10 cheque prints", "Basic bank templates", "Print history"],
    },
    standard: {
      label: "Standard Plan",
      firstMonth: "NPR 39",
      threeMonths: "NPR 99",
      sixMonths: "NPR 179",
      annual: "NPR 299",
      features: ["100 cheque prints/month", "All bank templates", "Export to PDF", "Email support"],
      bestValue: false,
    },
    business: {
      label: "Business Plan",
      firstMonth: "NPR 59",
      threeMonths: "NPR 149",
      sixMonths: "NPR 269",
      annual: "NPR 499",
      features: [
        "Unlimited prints",
        "All bank templates",
        "Bulk printing",
        "Priority support",
        "Custom templates",
      ],
      bestValue: true,
    },
    fonepay: {
      merchantName: "Reactify Software Technologies Pvt. Ltd.",
      qrCodeUrl: "/logos/fonepay-qr-placeholder.svg",
    },
  },
  cheque: {
    widthMm: 190.5,
    heightMm: 88.9,
    a4WidthMm: 210,
    a4HeightMm: 297,
  },
  trialConfig: {
    maxPrints: 10,
    daysDuration: 14,
  },
};
